name = "TaylorDiff"
uuid = "b36ab563-344f-407b-a36a-4f200bebf99c"
authors = ["Songchen Tan <i@tansongchen.com>"]
version = "0.1.1"

[deps]
ChainRules = "082447d4-558c-5d27-93f4-14fc19e9eca2"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ChainRulesOverloadGeneration = "f51149dc-2911-5acf-81fc-2076a2a81d4f"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
ZygoteRules = "700de1a5-db45-46bc-99cf-38207098b444"

[compat]
ChainRules = "1"
ChainRulesCore = "1"
ChainRulesOverloadGeneration = "0.1"
SymbolicUtils = "0.19, 0.20"
ZygoteRules = "0.2"
julia = "1.6"
