steps:
  - label: ":julia: Run tests"
    key: "test"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-test#v1:
          coverage: false
    agents:
      os: "linux"
      queue: "juliaecosystem"
      arch: "x86_64"
    timeout_in_minutes: 30

  - label: ":julia: Run benchmarks"
    key: "benchmark"
    command: "julia --project=benchmark benchmark/runbenchmarks.jl"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
    agents:
      os: "linux"
      queue: "juliaecosystem"
      exclusive: true
      arch: "x86_64"
    timeout_in_minutes: 30
